version: '3.8'

services:
  web:
    build: .
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
    env_file:
      - .env
